### ISSUE TITLE
Walk over nested references

### ISSUE THREAD

**Issue by jbardin** [mitchellh/reflectwalk#12]
We can't currently walk a data structure with contains pointer-pointers, e.g.

```
type T struct {
    N **int
}
````

While we can walk the more obscure pointer-to-interface, that will fail if the interface itself has a pointer, e.g. `*error`(assuming the error value has a pointer receiver). 

While very uncommon, it would be good if reflectwalk could traverse any combination of nested data structures without a panic.

**Comment by jbardin** [comment]
After a few attempts, I have a feeling that this isn't going to be doable in a general manner without a change to the API. 

Because pointers (and in a sense interfaces too) are "walked" implicitly, only providing a flag that the value we see came from a pointer, there's no way to have a consumer of the package know that we've dereferenced multiple levels.

**Comment by mitchellh** [comment]
This should be possible in one of two ways:

  1. Call `PointerEnter` multiple times (one for each level), which seems to make sense to me.

  2. A new interface that has an API similar to `PointerEnter` but with an `int` arg of the number of levels.

**Comment by jbardin** [comment]
Yeah, I have a version of #1 that works for reflectwalk, but that breaks the previous assumptions of 1 possible pointer per level (which copystructure uses).

Maybe it's not too big a deal, since any value that breaks reflectwalk consumers with this change would have just previously panicked in reflectwalk instead.

**Comment by mitchellh** [comment]
Yeah I'd rather fix that assumption in copystructure since it makes sense here.

**Comment by jbardin** [comment]
This was fixed via #13 and #15
